# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [35]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [9]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [10]:
arr = np.arange(10,52,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [13]:
id_mat = np.identity(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [18]:
random_number = np.random.rand()
print(random_number)

0.9605884744935244


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
from numpy import random 
X= random.normal(loc=0, scale=1, size=(25))
print(X)

[ 0.41755893  0.24473657  0.85473382 -1.72713238 -0.32714742 -0.72541396
  3.10178994  0.93783368 -1.88029519 -1.20745099 -2.3903536   0.24397472
 -0.2804593   0.08655009 -0.08975046  0.30344822  1.17816205 -0.416536
  1.06493653  1.37840201 -0.28125608 -0.00632417  1.95320809 -0.90048226
  0.25979014]


#### Create the following matrix:

In [17]:
arr = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(arr)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [26]:

values=np.linspace(0,1,100)
matrix =values.reshape(10,10)
print(matrix)

[[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
  0.06060606 0.07070707 0.08080808 0.09090909]
 [0.1010101  0.11111111 0.12121212 0.13131313 0.14141414 0.15151515
  0.16161616 0.17171717 0.18181818 0.19191919]
 [0.2020202  0.21212121 0.22222222 0.23232323 0.24242424 0.25252525
  0.26262626 0.27272727 0.28282828 0.29292929]
 [0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
  0.36363636 0.37373737 0.38383838 0.39393939]
 [0.4040404  0.41414141 0.42424242 0.43434343 0.44444444 0.45454545
  0.46464646 0.47474747 0.48484848 0.49494949]
 [0.50505051 0.51515152 0.52525253 0.53535354 0.54545455 0.55555556
  0.56565657 0.57575758 0.58585859 0.5959596 ]
 [0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
  0.66666667 0.67676768 0.68686869 0.6969697 ]
 [0.70707071 0.71717172 0.72727273 0.73737374 0.74747475 0.75757576
  0.76767677 0.77777778 0.78787879 0.7979798 ]
 [0.80808081 0.81818182 0.82828283 0.83838384 0.84848485 0.85858586
  0.86868687

#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
linear_spaced_array = np.linspace(0, 1, 20)
print(linear_spaced_array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [28]:
arr = np.arange(1, 26, 1).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
sub_arr = arr[2:,1:]
print(sub_arr)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [30]:
sub_arr = arr[2:,1:]
print(sub_arr)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
element = arr[3,4]
print(element)

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
arr[[0,1,2], [1]].reshape(-1,1)

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
arr[-1:]

array([[21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
arr[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [40]:
np.sum(arr)

325

#### Get the standard deviation of the values in mat

In [41]:
np.std(arr)

7.211102550927978

#### Get the sum of all the columns in mat

In [43]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!